// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"errors"
	"github.com/arran4/golang-wordwrap/cli"
	"github.com/arran4/golang-wordwrap/cmd"
)

var _ Cmd = (*Simple)(nil)

type Simple struct {
	*RootCmd
	Flags         *flag.FlagSet
	width         int
	height        int
	dpiStr        string
	fontname      string
	fontsizeStr   string
	textsource    string
	outfilename   string
	boxline       bool
	boxbox        bool
	yoverflow     int
	SubCommands   map[string]Cmd
	CommandAction func(c *Simple) error
}

type UsageDataSimple struct {
	*Simple
	Recursive bool
}

func (c *Simple) Usage() {
	err := executeUsage(os.Stderr, "simple_usage.txt", UsageDataSimple{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Simple) UsageRecursive() {
	err := executeUsage(os.Stderr, "simple_usage.txt", UsageDataSimple{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Simple) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			break
		}
		if strings.HasPrefix(arg, "-") && arg != "-" {
			name := arg
			value := ""
			hasValue := false
			if strings.Contains(arg, "=") {
				parts := strings.SplitN(arg, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			trimmedName := strings.TrimLeft(name, "-")
			switch trimmedName {

			case "width":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.width = iv

			case "height":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.height = iv

			case "dpiStr", "dpi":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.dpiStr = value

			case "fontname", "font":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.fontname = value

			case "fontsizeStr", "size":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.fontsizeStr = value

			case "textsource", "text":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.textsource = value

			case "outfilename", "out":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.outfilename = value

			case "boxline":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.boxline = b
				} else {
					c.boxline = true
				}

			case "boxbox":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.boxbox = b
				} else {
					c.boxbox = true
				}

			case "yoverflow":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.yoverflow = iv
			case "help", "h":
				c.Usage()
				return nil
			default:
				return fmt.Errorf("unknown flag: %s", name)
			}
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("simple failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewSimple() *Simple {
	set := flag.NewFlagSet("simple", flag.ContinueOnError)
	v := &Simple{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.IntVar(&v.width, "width", 400, "Doc width")

	set.IntVar(&v.height, "height", 600, "Doc height")

	set.StringVar(&v.dpiStr, "dpi", "180.0", "Doc dpi")

	set.StringVar(&v.fontname, "font", "goregular", "Text font")

	set.StringVar(&v.fontsizeStr, "size", "16.0", "font size")

	set.StringVar(&v.textsource, "text", "-", "File in or - for std input")

	set.StringVar(&v.outfilename, "out", "out.png", "file to write to in some cases this is ignored")

	set.BoolVar(&v.boxline, "boxline", false, "Box the line")

	set.BoolVar(&v.boxbox, "boxbox", false, "Box the box")

	set.IntVar(&v.yoverflow, "yoverflow", 0, "Y Overflow mode")
	set.Usage = v.Usage

	v.CommandAction = func(c *Simple) error {

		err := cli.SimpleWrapToImage(c.width, c.height, c.dpiStr, c.fontname, c.fontsizeStr, c.textsource, c.outfilename, c.boxline, c.boxbox, c.yoverflow)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			return fmt.Errorf("simple failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	v.SubCommands["usage"] = &InternalCommand{
		Exec: func(args []string) error {
			for _, arg := range args {
				if arg == "-deep" {
					v.UsageRecursive()
					return nil
				}
			}
			v.Usage()
			return nil
		},
		UsageFunc: v.Usage,
	}
	return v
}
